#include "app_assets.h"

BITMAP* background{};
BITMAP* buffer{};
DATAFILE* background_data{};
DATAFILE* bigchicken_data{};
DATAFILE* cursors_data{};
DATAFILE* chicken_data{};
DATAFILE* flyingchicken_data{};
DATAFILE* terrain_data{};
DATAFILE* gem_data{};
DATAFILE* giblet_data{};
DATAFILE* icons_data{};
DATAFILE* fonts_data{};
DATAFILE* modechooser_data{};
FONT* font_big{};
FONT* font_interface{};
SAMPLE* sound_alarm{};
SAMPLE* sound_gameover{};
SAMPLE* sound_gemcollect{};
SAMPLE* sound_highscore{};
SAMPLE* sound_menu{};
SAMPLE* sound_rocket{};
SAMPLE* sound_shotgun{};
SAMPLE* sound_tenderizer{};
